//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated from a template.
//
//     Manual changes to this file may cause unexpected behavior in your application.
//     Manual changes to this file will be overwritten if the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace MVCInBuiltFeatures
{
    using System;
    using System.Collections.Generic;
    
    public partial class SResults
    {
        public int ID { get; set; }
        public string sid { get; set; }
        public string result { get; set; }
        public string medicine { get; set; }
        public string present_illness { get; set; }
        public string vital_sign { get; set; }
        public System.DateTime date { get; set; }
    }
}
