// <auto-generated />
namespace MVCInBuiltFeatures.Migrations
{
    using System.CodeDom.Compiler;
    using System.Data.Entity.Migrations;
    using System.Data.Entity.Migrations.Infrastructure;
    using System.Resources;
    
    [GeneratedCode("EntityFramework.Migrations", "6.0.0-20911")]
    public sealed partial class editPrimaryKeyStudent1 : IMigrationMetadata
    {
        private readonly ResourceManager Resources = new ResourceManager(typeof(editPrimaryKeyStudent1));
        
        string IMigrationMetadata.Id
        {
            get { return "201603311610285_editPrimaryKeyStudent1"; }
        }
        
        string IMigrationMetadata.Source
        {
            get { return null; }
        }
        
        string IMigrationMetadata.Target
        {
            get { return Resources.GetString("Target"); }
        }
    }
}
